# Generated by Django 4.1.4 on 2023-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
